Website/models.py
from audioop import add
from .__init__ import create_app
from flask_pymongo import PyMongo
from flask import Flask, app, jsonify, request, flash

def postData(firstname, lastname, phonenumber, DOB, email, password1):
    flask_obj = create_app()
    Mongo = PyMongo(flask_obj)
    currentcollection = Mongo.db.Banking

    #email validation 
    if currentcollection.find_one({"email": email}):
        return jsonify({'error': "email already in use"}), 400
    else:
        currentcollection.insert({'firstname': firstname, 'lastname': lastname,
    'phonenumber': phonenumber,
    'DOB': DOB,
    'email': email,
    'password1': password1
    })
    return jsonify({'firstname': firstname, 'lastname': lastname,
    'phonenumber': phonenumber,
    'DOB': DOB,
    'email': email,
    'password1': password1
    })

# def validatelogin(email, password1):
#     flask_obj = create_app()
#     Mongo = PyMongo(flask_obj)
#     currentcollection = Mongo.db.Banking

#     a = currentcollection.find_one({'email': email})
#     if a:
#         if a({'password1': password1} == password1):
#             flash("logged in sucessfully", category= 'sucess')
#         else:
#             flash('incorrect password', category='error')
#     else:
#         flash('email not found', category='error') 
def pData(firstname, lastname, email, password1, DOB, address, city, Province, ZipCode, phonenumber, AccountNumber,
        accountType):
    flask_obj = create_app()
    Mongo = PyMongo(flask_obj)
    currentcollection = Mongo.db.Information
     #email validation 
    if currentcollection.find_one({"email": email}):
        return jsonify({'error': "email already in use"}), 400
    else:
        currentcollection.insert({'firstname': firstname, 'lastname': lastname, 'email': email,   
    'password1': password1,
    'DOB': DOB,
    'address': address,
    'city': city,
    'Province': Province,
    'ZipCode': ZipCode,
    'phonenumber': phonenumber,
    'AccountNumber': AccountNumber,
    'accountType': accountType
    })
    return jsonify({'firstname': firstname, 'lastname': lastname, 'email': email,   
    'password1': password1,
    'DOB': DOB,
    'address': address,
    'city': city,
    'Province': Province,
    'ZipCode': ZipCode,
    'phonenumber': phonenumber,
    'AccountNumber': AccountNumber,
    'accountType': accountType
    })

Website/__init__.py
# this file allows contents to be imported for the website 
from flask import Flask
from flask_pymongo import PyMongo


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'absgdhcj' #secret_key is used for authentication purpose especially, for sessions and cookies
    app.config['MONGO_URI'] = 'mongodb://localhost:27017/Information' #to link our mongo db Banking
    #PyMongo(app)
    

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    
    return app

Website/auth.py
from .__init__ import create_app
from flask import Blueprint, render_template, request, flash, jsonify
#from markupsafe import re
from flask_pymongo import PyMongo
from .models import postData, pData

auth = Blueprint('auth', __name__)

@auth.route('/login', methods= ['GET','POST'])
def login():
  if request.method == 'POST':
      email = request.form.get('email')
      password1 = request.form.get('password1')
      flask_obj = create_app()
      Mongo = PyMongo(flask_obj)
      currentcollection = Mongo.db.Information
      if currentcollection.find_one({'email': email}) and currentcollection.find_one({'password1': password1}):
          #flash(f'Successfully logged in as {email}' , category='sucess')
        return render_template('dashboard.html')
       

      else:
          return jsonify({'error': 'cant find'})
   
  return render_template("l.html")

@auth.route('/logout')
def logout():
    return render_template("landing.html")

@auth.route('/signup', methods=['GET','POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        phonenumber = request.form.get('phonenumber')
        DOB = request.form.get('DOB')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')


        if len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(firstname) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(lastname) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(phonenumber) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(DOB) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords dont match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            flash('Account created!', category='success')

       
        return postData(firstname, lastname, phonenumber, DOB, email, password1)

    return render_template("sign.html")

@auth.route('/s', methods=['GET','POST'])
def sign():
    if request.method == 'POST':
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        DOB = request.form.get('DOB')
        address = request.form.get('address')
        city = request.form.get('city')
        Province = request.form.get('Province')
        ZipCode = request.form.get('ZipCode')
        phonenumber = request.form.get('phonenumber')
        AccountNumber = request.form.get('AccountNumber')
        accountType = request.form.get('accountType')
       
        return pData(firstname, lastname, email, password1, DOB, address, city, Province, ZipCode, phonenumber, AccountNumber,
        accountType)

    return render_template("sign.html")

Website/views.py
from flask import Blueprint, render_template

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("dashboard.html")

    

Website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
      
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
      
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
    
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

Website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}

{% endblock %}

Website/templates/l.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="static/images/img-01.png" alt="IMG">
				</div>
                <form method="POST">
				<form class="login100-form validate-form">
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" id="password1" name="password1" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Login
						</button>
					</div>
                    
					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{{url_for('auth.sign')}}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
            </form>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/bootstrap/js/popper.js"></script>
	<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="static/js/main1.js"></script>

</body>
</html>

Website/templates/landing.html
<!doctype html>
<html lang="en">
  <head>
    <title>Primo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="static/fonts/icomoon/style.css">

    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/jquery-ui.css">
    <link rel="stylesheet" href="static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="static/css/owl.theme.default.min.css">

    <link rel="stylesheet" href="static/css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="static/css/bootstrap-datepicker.css">

    <link rel="stylesheet" href="static/fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="static/css/aos.css">

    <link rel="stylesheet" href="static/css/style.css">
    <script src="https://cdn.tailwindcss.com"></script>
    
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  

  <div id="overlayer"></div>
  <div class="loader">
    <div class="spinner-border text-primary" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>


  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
   
    
    <header class="site-navbar js-sticky-header site-navbar-target" role="banner">

      <div class="container">
        <div class="row align-items-center">
          
          <div class="col-6 col-xl-2">
            <a href="#"><img src="static/images/logo.png" class="d-inline" style="width: 100px;"></img></a>
          </div>

          <div class="col-12 col-md-10 d-none d-xl-block">
            <nav class="site-navigation position-relative text-right" role="navigation">

              <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                <li><a href="#home-section" class="nav-link">Home</a></li>
                <li>
                  <a href="#about-section" class="nav-link">About Us</a>
                 
                </li>
  
                <li><a href="#contact-section" class="nav-link">Contact</a></li>
       		
                    <li><a class="btn-sm" href="{{url_for('auth.login')}}">Create Account</a></li>
             
              </ul>
		
            </nav>
          </div>


          <div class="col-6 d-inline-block d-xl-none ml-md-0 py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle float-right"><span class="icon-menu h3"></span></a></div>

        </div>
      </div>
      
    </header>

  	
     
    <div class="site-blocks-cover overlay" style="background-image: url(static/images/hero2.jpg);" data-aos="fade" id="home-section">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-10 mt-lg-5 text-center">
            <div class="single-text owl-carousel">
              <div class="slide">
                <h1 class="text-uppercase" data-aos="fade-up">Banking Benefits</h1>
                <p class="mb-5 desc"  data-aos="fade-up" data-aos-delay="100">Primo Plus Points on every purchase with debit card.</p>
                <div data-aos="fade-up" data-aos-delay="100">
                </div>
              </div>

              <div class="slide">
                <h1 class="text-uppercase" data-aos="fade-up">Account Solutions</h1>
                <p class="mb-5 desc"  data-aos="fade-up" data-aos-delay="100">Open Savings or Checking Accounts and get Primo Privilege Points.</p>
              </div>

              <div class="slide">
                <h1 class="text-uppercase" data-aos="fade-up">Primo Privilege</h1>
                <p class="mb-5 desc"  data-aos="fade-up" data-aos-delay="100">Open account with zero dollar.</p>
              </div>

            </div>
          </div>
            
        </div>
      </div>

      <a href="#next" class="mouse smoothscroll">
        <span class="mouse-icon">
          <span class="mouse-wheel"></span>
        </span>
      </a>
    </div>  

   
    <section class="site-section border-bottom bg-light" id="services-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title mb-3">Our Services</h2>
          </div>
        </div>
        <div class="row" style="margin:auto; text-align:center">
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up">
            <div class="unit-4">
              <div class="unit-4-icon" >
                <img src="static/images/flaticon-svg/svg/001-wallet.svg" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4" style ="margin: auto;" >
              </div>
              <div>
                <h3>Primo Wallet</h3>
                <p>Save money with Primo Advantage Plan.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="100">
            <div class="unit-4">
              <div class="unit-4-icon">
                <img src="static/images/flaticon-svg/svg/006-credit-card.svg" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4" style ="margin: auto;">
              </div>
              <div>
                <h3>Debit Card</h3>
                <p>Primo Plus Points on every dollar spent on essential purchases.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="200">
            <div class="unit-4">
              <div class="unit-4-icon">
                <img src="static/images/flaticon-svg/svg/002-rich.svg" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4" style ="margin: auto;">
              </div>
              <div>
                <h3>Income Monitoring</h3>
                <p>Seamless advantage on Income Management.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="">
            <div class="unit-4">
              <div class="unit-4-icon">
                <img src="static/images/flaticon-svg/svg/003-notes.svg" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4" style ="margin: auto;">
              </div>
              <div>
                <h3>Cashback Rewards</h3>
                <p>Earn dollars spent on every purchase.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="100">
            <div class="unit-4">
              <div class="unit-4-icon">
                <img src="static/images/flaticon-svg/svg/004-cart.svg" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4" style ="margin: auto;">
              </div>
              <div>
                <h3>Primo Plus</h3>
                <p>Open account with minimum balance.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="200">
            <div class="unit-4">
              <div class="unit-4-icon">
                <img src="static/images/flaticon-svg/svg/005-megaphone.svg" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4" style ="margin: auto;">
              </div>
              <div>
                <h3>Primo Membership</h3>
                <p>Join Membership to enjoy Primo rewards points worldwide.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>

    
    
    <div class="site-section cta-big-image" id="about-section">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-8 text-center">
            <h2 class="section-title mb-3" data-aos="fade-up" data-aos-delay="">About Us</h2>
            <p class="lead" data-aos="fade-up" data-aos-delay="100">We are serving customers and driving growth thorugh our Primo Privilege Plans.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6 mb-5" data-aos="fade-up" data-aos-delay="">
            <figure class="circle-bg">
            <img src="static/images/hero_1.jpg" alt="Free Website Template by Free-Template.co" class="img-fluid">
            </figure>
          </div>
          <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="100">
            
            <h3 class="text-black mb-4">We Solve Your Financial Problem</h3>

            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>

            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            
          </div>
        </div>    
        
      </div>  
    </div>

    

    <section class="site-section bg-light" id="contact-section" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center">
            <h2 class="section-title mb-3">Contact Us</h2>
          </div>
        </div>
        <div class="row mb-5">
          


          <div class="col-md-4 text-center">
            <p class="mb-4">
              <span class="icon-room d-block h2 text-primary"></span>
              <span>203 Fake St. Mountain View, San Francisco, California, USA</span>
            </p>
          </div>
          <div class="col-md-4 text-center">
            <p class="mb-4">
              <span class="icon-phone d-block h2 text-primary"></span>
              <a href="#">+1 232 3235 324</a>
            </p>
          </div>
          <div class="col-md-4 text-center">
            <p class="mb-0">
              <span class="icon-mail_outline d-block h2 text-primary"></span>
              <a href="#">Primobank@primo.org</a>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mb-5">
          </div>
          
        </div>
      </div>
    </section>

  </div>
  <footer class="text-gray-600 body-font">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
      <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
        
        </svg>
   
        <img src="static/images/logo.png" class="d-inline" style="width: 100px;"></img>
      </a>
      <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2022 All Rights Reserved. 
      
      </p>
    </div>
  </footer> <!-- .site-wrap -->

  <script src="static/js/jquery-3.3.1.min.js"></script>
  <script src="static/js/jquery-ui.js"></script>
  <script src="static/js/popper.min.js"></script>
  <script src="static/js/bootstrap.min.js"></script>
  <script src="static/js/owl.carousel.min.js"></script>
  <script src="static/js/jquery.countdown.min.js"></script>
  <script src="static/js/jquery.easing.1.3.js"></script>
  <script src="static/js/aos.js"></script>
  <script src="static/js/jquery.fancybox.min.js"></script>
  <script src="static/js/jquery.sticky.js"></script>
  <script src="static/js/isotope.pkgd.min.js"></script>

  
  <script src="static/js/main.js"></script>

  
  </body>
</html>

Website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
	%}
	<form method="POST">
	  <h3 align="center">Login</h3>
	  <div class="form-group">
		<label for="email">Email Address</label>
		<input
		  type="email"
		  class="form-control"
		  id="email"
		  name="email"
		  placeholder="Enter email"
		/>
	  </div>
	  <div class="form-group">
		<label for="password">Password</label>
		<input
		  type="password"
		  class="form-control"
		  id="password1"
		  name="password1"
		  placeholder="Enter password"
		/>
	  </div>
	  <br />
	  <button type="submit" class="btn btn-primary">Login</button>
	</form>
	{% endblock %}
	

Website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstname"
      name="firstname"
      placeholder="Enter first name"
    />
  </div>

  <div class="form-group">
    <label for="lastname">First Name</label>
    <input
      type="text"
      class="form-control"
      id="lastname"
      name="lastname"
      placeholder="Enter first name"
    />
  </div>

  
  <div class="form-group">
    <label for="phonenumber">First Name</label>
    <input
      type="number"
      class="form-control"
      id="phonenumber"
      name="phonenumber"
      placeholder="Enter first name"
    />
  </div>

   
  <div class="form-group">
    <label for="DOB">First Name</label>
    <input
      type="date"
      class="form-control"
      id="DOB"
      name="DOB"
      placeholder="Enter first name"
    />
  </div>

  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}